language: node_js
sudo: required
dist: trusty
node_js:
  - '6'
cache:
  yarn: true
  directories:
    - node_modules
branches:
  except:
    - /^v\d/
before_install:
  - openssl aes-256-cbc -K $encrypted_638931912265_key -iv $encrypted_638931912265_iv -in Website-d2db09424cbb.json.enc -out Website-d2db09424cbb.json -d
install:
  - yarn install
  - yarn global add bower
  - bower install
# script:
  # - yarn run lint
  # - yarn run test
before_deploy:
  - yarn run build
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: Website-d2db09424cbb.json
  project: website-159123
  default: true
  on: master
