language: python
python:
  - "2.7"
sudo: required
branches:
  except:
    - /^v\d/
before_install:
  - openssl aes-256-cbc -K $encrypted_638931912265_key -iv $encrypted_638931912265_iv -in Website-d2db09424cbb.json.enc -out Website-d2db09424cbb.json -d

deploy:
  provider: gae
  skip_cleanup: true
  keyfile: Website-d2db09424cbb.json
  project: website-159123
  default: true
  on: master
