language: node_js
sudo: required
dist: trusty
addons:
  firefox: '46.0'
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
node_js:
  - '6'
  - '5'
  - '4'
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - openssl aes-256-cbc -K $encrypted_638931912265_key -iv $encrypted_638931912265_iv -in Website-d2db09424cbb.json.enc -out Website-d2db09424cbb.json -d
before_script:
  - npm install -g bower polymer-cli
  - bower install
#script:
  #- xvfb-run polymer test
deploy:
  provider: gae
  skip_cleanup: true
  keyfile: Website-d2db09424cbb.json
  project: website-159123
  default: true
  on: master
