runtime: python27
threadsafe: yes

handlers:
- url: /bower_components
  static_dir: build/bundled/bower_components
  secure: always

- url: /images
  static_dir: build/bundled/images
  secure: always

- url: /src
  static_dir: build/bundled/src
  secure: always

- url: /service-worker.js
  static_files: build/bundled/service-worker.js
  upload: build/bundled/service-worker.js
  secure: always

- url: /manifest.json
  static_files: build/bundled/manifest.json
  upload: build/bundled/manifest.json
  secure: always

- url: /.*
  static_files: build/bundled/index.html
  upload: build/bundled/index.html
  secure: always
  
skip_files:
- ^(.*/)?\.zip$
- ^(.*/)?\.bat$
- ^(.*/)?\.sh$
- ^(.*/)?\.md$
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?tests$
- ^(.*/)?test$
- ^(.*/)grunt\.js
- ^(.*/)node_modules/(.*/)?
- ^(.*/)bower_components/(.*/)?
- ^scripts/(.*/)?
- ^test/(.*/)?
- ^README\..*
- \.gitignore
- ^\.git/.*
- \.*\.lint$
- ^fabfile\.py
- ^testrunner\.py
