runtime: python27
threadsafe: yes

handlers:
- url: /bower_components
  static_dir: build/unbundled/bower_components
  secure: always

- url: /images
  static_dir: build/unbundled/images
  secure: always

- url: /src
  static_dir: build/unbundled/src
  secure: always

- url: /service-worker.js
  static_files: build/unbundled/service-worker.js
  upload: build/unbundled/service-worker.js
  secure: always

- url: /manifest.json
  static_files: build/unbundled/manifest.json
  upload: build/unbundled/manifest.json
  secure: always

- url: /.*
  static_files: build/unbundled/index.html
  upload: build/unbundled/index.html
  secure: always

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?\.bak$
- ^node_modules/(?!node\.js$).*
