runtime: python27
threadsafe: yes

handlers:

- url: /bower_components
  static_dir: bower_components
  secure: always

- url: /css
  static_dir: css
  secure: always

- url: /elements
  static_dir: elements
  secure: always

- url: /images
  static_dir: images
  secure: always

- url: /js
  static_dir: js
  secure: always

- url: /humans.txt
  static_files: humans.txt
  upload: humans.txt
  secure: always

- url: /manifest.json
  static_files: manifest.json
  upload: manifest.json
  mime_type: application/manifest+json
  secure: always

- url: /
  static_files: index.html
  upload: index\.html

skip_files:
  - ^(.*/)?#.*#$
  - ^(.*/)?.*~$
  - ^(.*/)?.*\.py[co]$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.graffle$
  - ^(.*/)?.*/RCS/.*$
  - ^(.*/)?\..*$
  - gulpfile.js
  - test*
  - bower_components/[^/]+/bower_components/.*$
  - bower_components/(.+/)+(test/|demo/|README|AUTHORS|CONTRIBUTING|PATENTS|Makefile)
